name = "summer-pond-ddf9"
main = "_worker.js"
compatibility_date = "2025-11-04"
keep_vars = true

[[kv_namespaces]]
binding = "KV"			#KV绑定名默认不可修改

id = "2353910d14854dca933ff372b68161f0"				#KV数据库id



